name: LHCI-post-check
jobs:
  # This posts a check
  assert-on-budget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse on urls and validate with budgets.json
        uses: ./
        with:
          urls: 'https://alekseykulikov.com/'
          ghtoken: ${{ secrets.GITHUB_TOKEN }}
